export const USER_DATA_KEY = 'user_data';

export const AUTH_ERRORS = {
  INVALID_INPUT: 'INVALID_INPUT_VALUE',
  UNSUPPORTED_JWT: 'UNSUPPORTED_JWT',
  UNAUTHENTICATED_USER: 'UNAUTHENTICATED_USER',
  INVALID_JWT_SIGNATURE: 'INVALID_JWT_SIGNATURE',
  EXPIRED_REFRESH_TOKEN: 'EXPIRED_REFRESH_TOKEN',
} as const;
